force-app/main/default/objects/Auth_Provider_Log__c/Auth_Provider_Log__c.object-meta.xml
<CustomObject>
    <description>Object to store (error) informaton for custom Auth Providers</description>
    <label>Auth Provider Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Provider Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/objects/Auth_Provider_Log__c/fields/Auth_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Auth_Provider_Name__c</fullName>
    <label>Auth Provider Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Auth_Provider_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Auth_Provider_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Auth_Provider_User_Mapping__c/Auth_Provider_User_Mapping__c.object-meta.xml
<CustomObject>
    <description>Object to store the mapping between a Salesforce User and the external system&apos;s user Id referenced in the a custom Auth Provider.</description>
    <label>Auth Provider User Mapping</label>
    <nameField>
        <displayFormat>MAP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Provider User Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/objects/Auth_Provider_User_Mapping__c/fields/Auth_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Auth_Provider_Name__c</fullName>
    <description>The API Name of the auth provider that will use this mapping</description>
    <inlineHelpText>The API Name of the auth provider that will use this mapping</inlineHelpText>
    <label>Auth Provider Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Auth_Provider_User_Mapping__c/fields/Last_Auth_Provider_Log__c.field-meta.xml
<CustomField>
    <fullName>Last_Auth_Provider_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>In case a log record has been created for this user/auth provider combination, link that last log record</description>
    <inlineHelpText>In case a log record has been created for this user/auth provider combination, link that last log record</inlineHelpText>
    <label>Last Auth Provider Log</label>
    <referenceTo>Auth_Provider_Log__c</referenceTo>
    <relationshipLabel>Auth Provider User Mapping</relationshipLabel>
    <relationshipName>Auth_Provider_User_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/package/objects/Auth_Provider_User_Mapping__c/fields/Last_Login_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Login_Date__c</fullName>
    <description>The last time a user logged in</description>
    <label>Last Login Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Auth_Provider_User_Mapping__c/fields/Number_of_Logins__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Logins__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of times this user logged in</description>
    <label>Number of Logins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/objects/Auth_Provider_User_Mapping__c/fields/Target_User_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Target_User_Identifier__c</fullName>
    <description>The identifier of the user on the authentication server, can be username or federation identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>The identifier of the user on the authentication server, can be username or federation identifier</inlineHelpText>
    <label>Target User Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/objects/Auth_Provider_User_Mapping__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Auth_Provider_User_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AuthProviderUtilTest.cls
/**
 * @author      Justus van den Berg (jfwberg@gmail.com)
 * @date        May 2023
 * @copyright   (c) 2023 Justus van den Berg
 * @license     MIT (See LICENSE file in the project root)
 * @description Class containing the Auth Provider Utilities Test Methods
 */
@IsTest
private with sharing class AuthProviderUtilTest {
	
	// Test data values
	private static String authProviderName	= 'myAuthProvider';
	private static String userId			= UserInfo.getUserId();
	private static String targetUserId		= UserInfo.getUserId().toUpperCase();
	private static String logId				= EncodingUtil.convertToHex(Crypto.generateAESKey(128));
	private static String message			= '(Error) Message content';


	/**
	 * @description Method to test inserting a log without an existing mapping record
	 */
	@IsTest
	static void testUtilitiesWithoutMapping(){
		
		// Method to insert an (error) log. Can be used for a success as well, but that should be checked in the external system
		AuthProviderUtil.insertLog(
			authProviderName,
			userId,
			logId,
			message
		);

		// Update the mapping details on the user mapping record
		AuthProviderUtil.updateMappingLoginDetails(
			authProviderName,
			userId
		);

		// Assert the new log is inserted
		System.assertEquals(
			1,
			[SELECT COUNT() FROM Auth_Provider_Log__c],
			'Expected a single log record'
		);
	}


	/**
	 * @description Method to test inserting a log without with an existing mapping record
	 *              - Creates a log and links the related mapping record to that log
	 *              - Updates the mapping record to simulate a succesful login (token request)
	 */
	@IsTest
	static void testUtilitiesWithMapping(){
		
		// Create a new user mapping record
		Auth_Provider_User_Mapping__c userMapping = new Auth_Provider_User_Mapping__c(
			Auth_Provider_Name__c = authProviderName,
			User__c = userId,
			Target_User_Identifier__c = targetUserId
		);
		insert userMapping;

		// Method to insert an (error) log. Can be used for a success as well, but that should be checked in the external system
		AuthProviderUtil.insertLog(
			authProviderName,
			userId,
			logId,
			message
		);

		// Query the user mapping, this will fail if there is no user mapping logged
		userMapping = [	SELECT Id, Last_Auth_Provider_Log__c, Last_Login_Date__c, Number_of_Logins__c
						FROM Auth_Provider_User_Mapping__c WHERE Last_Auth_Provider_Log__c != null LIMIT 1
					];

		// Validate expected updates on the mapping record
		System.assertEquals(true , userMapping.Last_Auth_Provider_Log__c!= null,'Expected no auth provider log');
		System.assertEquals(true , userMapping.Last_Login_Date__c		== null,'Expected no last login date to be populated');
		System.assertEquals(true , userMapping.Number_of_Logins__c		== 0,	'Expected number of logins to be 0');
		
		// Update the mapping details on the user mapping record
		AuthProviderUtil.updateMappingLoginDetails(
			authProviderName,
			userId
		);

		// Query the user mapping again now the login details have been updated
		userMapping = [	SELECT Id, Last_Auth_Provider_Log__c, Last_Login_Date__c, Number_of_Logins__c
						FROM Auth_Provider_User_Mapping__c WHERE Last_Auth_Provider_Log__c != null LIMIT 1
					];

		// Validate expected updates on the mapping record
		System.assertEquals(true , userMapping.Last_Login_Date__c	!= null,'Expected a last login date to be populated');
		System.assertEquals(true , userMapping.Number_of_Logins__c	== 1,	'Expected number of logins to be 1');
	}


	/**
	 * @description Method to test the auth provider name validation logic
	 */
	@IsTest
	static void testAuthProviderNameValidation(){
		try{
			// Don't ignore the validation in a test
			AuthProviderUtil.ignoreValidationInTest = false;

			// Run validation
			AuthProviderUtil.validateAuthProviderName(
				Auth_Provider_Log__c.Auth_Provider_Name__c,	
				new SObject[]{new Auth_Provider_Log__c(Auth_Provider_Name__c = 'randomValueHereXYZ')}
			);
		}catch(Exception e){
			// Validate the exception message
			System.assertEquals(
				String.format(
					AuthProviderUtil.INVALID_AUTH_PROVIDER_MSG,
					new String[]{'randomValueHereXYZ'}
				),
				e.getMessage(),
				'Unexpected validation message'
			);
		}
	}


	/**
	 * @description Method to test the log input validation logic
	 */
	@IsTest
	static void testValidateLogInput(){
		try{
			AuthProviderUtil.insertLog(null,null,null,null);
		}catch(Exception e){
			// Validate the exception message
			System.assertEquals(
				AuthProviderUtil.LOG_INPUT_VALIDATION_MSG,
				e.getMessage(),
				'Unexpected validation message'
			);
		}
	}
}